/** Common ISO 4217 codes for FMV local currency selection (extend as needed). */
export const FMV_COMMON_CURRENCIES = [
  { code: "USD", label: "USD — US dollar" },
  { code: "EUR", label: "EUR — Euro" },
  { code: "GBP", label: "GBP — Pound sterling" },
  { code: "AUD", label: "AUD — Australian dollar" },
  { code: "CAD", label: "CAD — Canadian dollar" },
  { code: "CHF", label: "CHF — Swiss franc" },
  { code: "CNY", label: "CNY — Chinese yuan" },
  { code: "CZK", label: "CZK — Czech koruna" },
  { code: "DKK", label: "DKK — Danish krone" },
  { code: "HKD", label: "HKD — Hong Kong dollar" },
  { code: "HUF", label: "HUF — Hungarian forint" },
  { code: "ILS", label: "ILS — Israeli shekel" },
  { code: "INR", label: "INR — Indian rupee" },
  { code: "JPY", label: "JPY — Japanese yen" },
  { code: "KRW", label: "KRW — South Korean won" },
  { code: "MXN", label: "MXN — Mexican peso" },
  { code: "NOK", label: "NOK — Norwegian krone" },
  { code: "NZD", label: "NZD — New Zealand dollar" },
  { code: "PLN", label: "PLN — Polish złoty" },
  { code: "RON", label: "RON — Romanian leu" },
  { code: "SEK", label: "SEK — Swedish krona" },
  { code: "SGD", label: "SGD — Singapore dollar" },
  { code: "TRY", label: "TRY — Turkish lira" },
  { code: "ZAR", label: "ZAR — South African rand" },
] as const;
