/** Curated pharma / biotech names for mention detection in headlines. */
export type PharmaCompanyEntry = {
  id: string;
  displayName: string;
  aliases: string[];
};

export const PHARMA_COMPANIES: PharmaCompanyEntry[] = [
  { id: "pfizer", displayName: "Pfizer", aliases: ["Pfizer"] },
  { id: "merck", displayName: "Merck", aliases: ["Merck", "MSD", "Merck & Co"] },
  { id: "novartis", displayName: "Novartis", aliases: ["Novartis"] },
  { id: "roche", displayName: "Roche", aliases: ["Roche", "Genentech"] },
  {
    id: "astrazeneca",
    displayName: "AstraZeneca",
    aliases: ["AstraZeneca"],
  },
  {
    id: "johnson-johnson",
    displayName: "Johnson & Johnson",
    aliases: ["Johnson & Johnson", "J&J", "Janssen"],
  },
  { id: "sanofi", displayName: "Sanofi", aliases: ["Sanofi"] },
  { id: "gsk", displayName: "GSK", aliases: ["GSK", "GlaxoSmithKline", "Glaxo"] },
  { id: "lilly", displayName: "Eli Lilly", aliases: ["Eli Lilly", "Lilly"] },
  { id: "abbvie", displayName: "AbbVie", aliases: ["AbbVie"] },
  { id: "amgen", displayName: "Amgen", aliases: ["Amgen"] },
  { id: "gilead", displayName: "Gilead", aliases: ["Gilead", "Kite Pharma"] },
  {
    id: "bms",
    displayName: "Bristol Myers Squibb",
    aliases: ["Bristol Myers Squibb", "Bristol-Myers Squibb", "BMS"],
  },
  { id: "moderna", displayName: "Moderna", aliases: ["Moderna"] },
  { id: "biontech", displayName: "BioNTech", aliases: ["BioNTech"] },
  { id: "regeneron", displayName: "Regeneron", aliases: ["Regeneron"] },
  { id: "bayer", displayName: "Bayer", aliases: ["Bayer"] },
  {
    id: "boehringer",
    displayName: "Boehringer Ingelheim",
    aliases: ["Boehringer Ingelheim", "Boehringer"],
  },
  { id: "takeda", displayName: "Takeda", aliases: ["Takeda"] },
  { id: "novo-nordisk", displayName: "Novo Nordisk", aliases: ["Novo Nordisk"] },
  { id: "biogen", displayName: "Biogen", aliases: ["Biogen"] },
  { id: "vertex", displayName: "Vertex", aliases: ["Vertex"] },
  { id: "astellas", displayName: "Astellas", aliases: ["Astellas"] },
  { id: "daiichi", displayName: "Daiichi Sankyo", aliases: ["Daiichi Sankyo", "Daiichi"] },
  { id: "eisai", displayName: "Eisai", aliases: ["Eisai"] },
  { id: "otsuka", displayName: "Otsuka", aliases: ["Otsuka"] },
  { id: "ucb", displayName: "UCB", aliases: ["UCB"] },
  { id: "ipsen", displayName: "Ipsen", aliases: ["Ipsen"] },
  { id: "servier", displayName: "Servier", aliases: ["Servier"] },
  { id: "tevapharma", displayName: "Teva", aliases: ["Teva Pharmaceutical", "Teva"] },
  { id: "viatris", displayName: "Viatris", aliases: ["Viatris", "Mylan"] },
  { id: "organon", displayName: "Organon", aliases: ["Organon"] },
  { id: "csl", displayName: "CSL", aliases: ["CSL Limited", "CSL Behring"] },
  { id: "alexion", displayName: "Alexion", aliases: ["Alexion"] },
  { id: "illumina", displayName: "Illumina", aliases: ["Illumina"] },
  {
    id: "thermofisher",
    displayName: "Thermo Fisher",
    aliases: ["Thermo Fisher", "Thermo Fisher Scientific"],
  },
  { id: "danaher", displayName: "Danaher", aliases: ["Danaher"] },
  { id: "iqvia", displayName: "IQVIA", aliases: ["IQVIA"] },
  { id: "parexel", displayName: "Parexel", aliases: ["Parexel"] },
  { id: "syneos", displayName: "Syneos Health", aliases: ["Syneos Health", "Syneos"] },
  { id: "incyte", displayName: "Incyte", aliases: ["Incyte"] },
  { id: "biomarin", displayName: "BioMarin", aliases: ["BioMarin"] },
  { id: "seagen", displayName: "Seagen", aliases: ["Seagen"] },
  { id: "alnylam", displayName: "Alnylam", aliases: ["Alnylam"] },
  { id: "sarepta", displayName: "Sarepta", aliases: ["Sarepta"] },
  { id: "ionis", displayName: "Ionis", aliases: ["Ionis"] },
  {
    id: "crispr",
    displayName: "CRISPR Therapeutics",
    aliases: ["CRISPR Therapeutics", "CRISPR"],
  },
  { id: "editas", displayName: "Editas", aliases: ["Editas Medicine", "Editas"] },
  {
    id: "intellia",
    displayName: "Intellia",
    aliases: ["Intellia Therapeutics", "Intellia"],
  },
  { id: "bluebird", displayName: "bluebird bio", aliases: ["bluebird bio", "bluebird"] },
  { id: "uniqure", displayName: "uniQure", aliases: ["uniQure"] },
  { id: "grunenthal", displayName: "Grünenthal", aliases: ["Grünenthal", "Grunenthal"] },
  { id: "chiesi", displayName: "Chiesi", aliases: ["Chiesi"] },
  { id: "menarini", displayName: "Menarini", aliases: ["Menarini"] },
  { id: "fresenius", displayName: "Fresenius", aliases: ["Fresenius Kabi", "Fresenius"] },
  { id: "sandoz", displayName: "Sandoz", aliases: ["Sandoz"] },
  { id: "celltrion", displayName: "Celltrion", aliases: ["Celltrion"] },
  {
    id: "samsung-bio",
    displayName: "Samsung Biologics",
    aliases: ["Samsung Biologics", "Samsung Bioepis"],
  },
  { id: "lonza", displayName: "Lonza", aliases: ["Lonza"] },
  { id: "catalent", displayName: "Catalent", aliases: ["Catalent"] },
  { id: "wuxi", displayName: "WuXi", aliases: ["WuXi AppTec", "WuXi Biologics", "WuXi"] },
  { id: "kelun", displayName: "Kelun", aliases: ["Kelun-Biotech", "Kelun", "Kelun Biotech"] },
  {
    id: "hengrui",
    displayName: "Hengrui",
    aliases: ["Hengrui Medicine", "Jiangsu Hengrui"],
  },
  { id: "beigene", displayName: "BeiGene", aliases: ["BeiGene", "BeOne Medicines"] },
  { id: "hutchmed", displayName: "Hutchmed", aliases: ["Hutchmed", "Hutchison China MediTech"] },
  { id: "legend", displayName: "Legend Biotech", aliases: ["Legend Biotech"] },
  { id: "argenx", displayName: "argenx", aliases: ["argenx"] },
  { id: "genmab", displayName: "Genmab", aliases: ["Genmab"] },
  { id: "galapagos", displayName: "Galapagos", aliases: ["Galapagos"] },
];
