-- Seed question library (56 questions, data v1.2)
-- Source: supabase/seed/question_library_data.json

-- JSON includes grid questions; extend enum before insert
alter table question_library
  drop constraint if exists question_library_question_type_check;

alter table question_library
  add constraint question_library_question_type_check
  check (
    question_type in (
      'single',
      'multi',
      'open',
      'numeric',
      'scale',
      'statement',
      'grid'
    )
  );

insert into question_library (
  display_id,
  question_text,
  question_type,
  answer_options,
  category,
  tags,
  sector,
  methodology,
  language,
  notes,
  is_locked,
  status,
  approved_by,
  approved_at
)
values
  ('INTRO-001', 'Good morning / afternoon, my name is [INSERT NAME] and I''m calling on behalf of Day One Strategy, an independent market research agency acting on behalf of a pharmaceutical company. We are conducting a market research study, which is sponsored by a pharmaceutical company, and we are talking to people who have been diagnosed with certain conditions to understand more around how they treat and manage their disease and to gain your thoughts and opinions of current and potential new treatments, which may or may not come to market. If the study is appropriate for you, we would like you to take part in a [XX]-minute interview, which will take the form of an online one-on-one interview. In appreciation of your time, you will be provided an honorarium of [INCENTIVE].', 'statement', '[]'::jsonb, 'introduction', array['intro', 'qual', 'recruiter-verbal', 'patient']::text[], array['Healthcare']::text[], array['IDI', 'Focus Group']::text[], 'en', 'QUAL ONLY. Recruiter verbal opening for patient / consumer studies. Customise: [INSERT NAME] = recruiter name; [XX] = interview duration in minutes; [INCENTIVE] = honorarium amount.', true, 'approved', null, null),
  ('INTRO-002', 'Good morning / afternoon, my name is [INSERT NAME] and I''m calling on behalf of Day One Strategy, an independent market research agency acting on behalf of a pharmaceutical company. We are conducting a market research study, which is sponsored by a pharmaceutical company, and we are talking to healthcare providers about their diagnosis and treatment of a [INSERT CONDITION AREA]. We are interested in your views and experiences with diagnosing and treating this patient group and your thoughts and opinions of current and potential new treatments, which may or may not come to market. If the study is appropriate for you, we would like you to take part in a [XX]-minute interview, which will take the form of an online one-on-one interview. In appreciation of your time, you will be provided an honorarium of [INCENTIVE].', 'statement', '[]'::jsonb, 'introduction', array['intro', 'qual', 'recruiter-verbal', 'hcp']::text[], array['Healthcare']::text[], array['IDI', 'Focus Group']::text[], 'en', 'QUAL ONLY. Recruiter verbal opening for HCP studies. Customise: [INSERT NAME]; [INSERT CONDITION AREA]; [XX] = interview duration; [INCENTIVE] = honorarium.', true, 'approved', null, null),
  ('INTRO-003', 'Thank you very much for your interest in participating in this research. This study is being conducted by Day One Strategy, an independent healthcare market research company, on behalf of a pharmaceutical company. If this study is appropriate for you, we would like you to take part in a [XX]-minute online survey. We would like you to know: This market research is aimed to gain your perspective and is not intended to be promotional. Participation is voluntary and you can refuse to answer questions or withdraw from the survey at any time. In appreciation for your time, you will be provided an honorarium.', 'statement', '[]'::jsonb, 'introduction', array['intro', 'quant', 'survey', 'online']::text[], null, array['Survey', 'Online Community']::text[], 'en', 'QUANT ONLY. Self-completion survey introduction. Customise: [XX] = survey duration in minutes.', true, 'approved', null, null),
  ('DISC-001', 'Day One is the data controller for this study. We want to assure you we will comply with all relevant codes of conduct and legislation for confidentiality in market research including: US - PMRG / PBIRG and MRS (Market Research Society). We will not store your name and contact details. In order to have your anonymized data removed please contact your recruiter with this job number [PROJECT NUMBER] so they can advise us. Your personal information will only be used for research purposes and will not be passed to any other organization without your permission with the exception of third-party service providers. You will remain anonymous to the pharmaceutical company unless you give permission to be identified. The processing will be based solely on your consent, which you may withdraw at any time. We won''t keep any personal data you give us for longer than 5 years. This market research is aimed to gain your views and is not intended to be promotional. Participation is voluntary and you can withdraw from the interview/survey at any time. Day One''s privacy policy can be found here: https://www.dayonestrategy.com/privacy', 'statement', '[]'::jsonb, 'consent', array['disclaimer', 'data protection', 'PMRG', 'MRS', 'privacy', 'US']::text[], null, null, 'en', 'Required for all US studies. Customise: [PROJECT NUMBER] = project job number (e.g. 260138). Do not edit legal language.', true, 'approved', null, null),
  ('CON-001', 'This research is double-blinded, meaning that the pharmaceutical company sponsoring the research does not know who you are, & you will not learn the name of the sponsoring company. Based on your consent, the sponsoring pharmaceutical company will receive anonymized / aggregated written report of the findings.

Do you agree to waive your right to learn the name of the sponsoring company on this basis?', 'single', '[{"text":"Yes, I agree to waive my right to learn the name of the sponsoring company on this basis","terminate":false},{"text":"No, I do not wish to waive my right to learn the name of the sponsoring company on this basis","terminate":true}]'::jsonb, 'consent', array['consent', 'double-blind', 'sponsor blinding', 'compliance']::text[], null, null, 'en', 'Required for all double-blinded pharmaceutical studies. ''No'' = THANK & CLOSE. Do not edit wording.', true, 'approved', null, null),
  ('CON-002', 'In order to comply with the USA Sunshine Act and for transparency purposes, in the event that anyone from the sponsoring client company is able to identify you during the course of the interview or if you are able to identify the sponsoring client company, we are obliged to pass to our client the amount of the compensation that you will receive for participating as well as your contact information. These details may be made publicly available or reported as legally required by our client.

As a result of this information, can you please confirm that in the event anyone from the sponsoring client identifies you or you identify the company, you agree that it is acceptable for these details to be passed on to them?', 'single', '[{"text":"Yes","terminate":false},{"text":"No","terminate":true}]'::jsonb, 'consent', array['consent', 'sunshine act', 'HCP', 'compensation disclosure', 'US']::text[], array['Healthcare']::text[], null, 'en', 'HCP studies only (US double-blinded). Required for Sunshine Act compliance — HCPs only. ''No'' = THANK & CLOSE. Do not edit legal wording.', true, 'approved', null, null),
  ('CON-003', 'We are obliged to pass on to our client details of adverse events and any complaints linked to one of the client''s products mentioned during the course of the market research study. Although what you say will, of course, be treated in the strictest confidence, if during the discussion you mention an adverse event or a complaint linked to a product in a specific patient or group of patients, we will need to report it, even if you have already reported it directly to the company or the regulatory authorities. In this situation, you will be asked if you are willing to waive the confidentiality given to you under the market research codes of conduct in relation to that adverse event and/or product complaint. Anything you say during the interview will remain confidential and you can decide to remain anonymous if you prefer. All other information that you provide as part of this study will continue to remain confidential.

On this basis, do you agree to participate in this research project?', 'single', '[{"text":"Yes","terminate":false},{"text":"No","terminate":true}]'::jsonb, 'consent', array['consent', 'adverse event', 'pharmacovigilance', 'compliance']::text[], array['Healthcare']::text[], null, 'en', 'Required for all pharmaceutical studies. ''No'' = THANK & CLOSE. Do not edit wording.', true, 'approved', null, null),
  ('CON-004', 'Interviews will be viewed and recorded on the Discuss.io platform. They may be listened to live by members of the sponsoring pharmaceutical company. [Note: agreement to live viewing is completely voluntary, and you can still take part even if you decline to live viewing]

Are you happy to proceed on this basis?', 'single', '[{"text":"I am happy to be observed by the client with camera","terminate":false},{"text":"I am happy to be observed by the client, without camera","terminate":false},{"text":"I am NOT happy to be observed by the client","terminate":false}]'::jsonb, 'consent', array['consent', 'recording', 'live viewing', 'qual', 'discuss.io']::text[], null, array['IDI', 'Focus Group']::text[], 'en', 'QUAL ONLY. All three options CONTINUE — none terminate. Respondents who select ''NOT happy'' are eligible for in-field interviews only. Record response for fieldwork team.', true, 'approved', null, null),
  ('CON-005', 'Day One Strategy may upload the interview to Versive, CoLoop, or ArgonAI for analysis. Versive, CoLoop, or ArgonAI are closed AI platforms used for analysis and your data will not be shared outside of the platforms, nor will the AI learn from your data. Privacy policies can be accessed here (https://www.getversive.com/privacy; https://genei.notion.site/Privacy-policy-c1fe81d698794f6ab559812dea45b84d; https://argon-ai.com/privacy-policy)

Are you happy to proceed with the interview on this basis?', 'single', '[{"text":"Yes","terminate":false},{"text":"No","terminate":true}]'::jsonb, 'consent', array['consent', 'AI analysis', 'Versive', 'CoLoop', 'ArgonAI', 'qual']::text[], null, array['IDI', 'Focus Group']::text[], 'en', 'QUAL ONLY. Consent for AI-assisted transcript analysis via Versive, CoLoop, or ArgonAI closed platforms. ''No'' = THANK & CLOSE. Keep privacy policy URLs current.', true, 'approved', null, null),
  ('CON-006', 'Day One Strategy may upload anonymous transcripts to our licensed model of Chat GPT for analysis purposes. We have a secure license and the AI is not trained on your data. Data is deleted from Chat GPT following the close of the project.

Do you consent to this analysis method?', 'single', '[{"text":"Yes","terminate":false},{"text":"No","terminate":true}]'::jsonb, 'consent', array['consent', 'AI analysis', 'ChatGPT', 'qual', 'anonymous transcripts']::text[], null, array['IDI', 'Focus Group']::text[], 'en', 'QUAL ONLY. Consent for anonymous transcript upload to Day One''s licensed ChatGPT model. ''No'' = THANK & CLOSE.', true, 'approved', null, null),
  ('CON-007', 'Day One Strategy may want to use your interview recording for internal training purposes. [This is entirely voluntary, and you can still take part in the study if you decline this]

Do you consent to your interview recording being used for Day One Strategy''s internal training purposes?', 'single', '[{"text":"Yes","terminate":false},{"text":"No","terminate":false}]'::jsonb, 'consent', array['consent', 'internal training', 'recording', 'qual', 'voluntary']::text[], null, array['IDI', 'Focus Group']::text[], 'en', 'QUAL ONLY. Fully voluntary — both Yes and No proceed. Flag ''No'' responses so fieldwork team excludes from training materials.', true, 'approved', null, null),
  ('CON-008', 'Re-contact permission for project purposes. Please indicate your consent for each of the following.', 'grid', '[{"text":"I give Day One permission to re-contact me with regard to my involvement in this study | Yes | No"},{"text":"I give Day One and the sponsoring pharmaceutical company permission to use clips of my recordings (audio and/or video) in original language or translated, for the purpose of internal training post research (educational, non-promotional use only) | Yes | No"},{"text":"I give Day One permission to pass anonymized quotes taken out of my video / audio clips, in original language or translated to the sponsoring pharma company and its affiliates and their third-party suppliers for internal or external use limited to educational and informative (non-promotional) use | Yes | No"}]'::jsonb, 'consent', array['consent', 'recontact', 'recording clips', 'quotes', 'qual']::text[], null, array['IDI', 'Focus Group']::text[], 'en', 'QUAL ONLY. Grid question — all Yes/No combinations proceed. Record all three responses separately. All to complete. Do not edit wording.', true, 'approved', null, null),
  ('CON-009', 'The session will be watched as it happens. The recording will only be available to market research agency and clients in Commercial roles including Market Research, Marketing, Market Access and Medical. [Note: agreement to live viewing is totally voluntary, and you can still take part even if you decline to live viewing]

Do you agree to participate on this basis? Please select one.', 'single', '[{"text":"Yes","terminate":false},{"text":"No","terminate":false}]'::jsonb, 'consent', array['consent', 'live viewing', 'final consent form']::text[], null, array['IDI', 'Focus Group']::text[], 'en', 'QUAL ONLY. Final consent form — live viewing consent. Both options proceed; ''No'' is flagged. Part of the written respondent consent document.', true, 'approved', null, null),
  ('CON-010', 'I agree to allow Day One Strategy @ 33 Foley Street, W1W 7TL to pass on video / audio recordings from my participation to their client in Commercial roles including Market Research, Marketing, Market Access and Medical. [Note: agreement to audio and video recording is totally voluntary and you can still take part even if you decline to pass on your video / audio to the pharmaceutical client]

Do you agree to participate on this basis? Please select one.', 'single', '[{"text":"Yes","terminate":false},{"text":"No","terminate":false}]'::jsonb, 'consent', array['consent', 'recording', 'video', 'audio', 'final consent form']::text[], null, array['IDI', 'Focus Group']::text[], 'en', 'QUAL ONLY. Final consent form — A/V recording consent. Both options proceed; ''No'' is flagged. Part of the written respondent consent document. Do not edit legal text.', true, 'approved', null, null),
  ('CON-011', 'Any stimulus materials shown during the course of this market research is confidential and for exploratory purposes only, and not intended to be promotional. Some of the information shown in the materials may be hypothetical, until either the results of clinical trials are verified, or regulatory submissions known.

Do you agree to participate on this basis? Please select one.', 'single', '[{"text":"Yes","terminate":false},{"text":"No","terminate":true}]'::jsonb, 'consent', array['consent', 'stimulus', 'confidentiality', 'regulatory', 'final consent form']::text[], null, null, 'en', 'Final consent form. ''No'' = TERMINATE. Required for any study using stimulus materials.', true, 'approved', null, null),
  ('CON-012', 'I understand that I will see sensitive and confidential material during the pre-task and interview and agree not to share with anyone.

Do you agree to participate on this basis? Please select one.', 'single', '[{"text":"Yes","terminate":false},{"text":"No","terminate":true}]'::jsonb, 'consent', array['consent', 'confidentiality', 'NDA', 'final consent form']::text[], null, null, 'en', 'Final consent form. ''No'' = TERMINATE. Required on all projects with confidential stimulus.', true, 'approved', null, null),
  ('EXC-001', 'Are you, or any member of your household, employed by the pharmaceutical industry on a full-time or consultancy basis, or is any member of your household employed by a communication or advertising agency related to pharmaceutical products?', 'single', '[{"text":"Yes (write in: what role and for which company)","terminate":false},{"text":"No","terminate":false}]'::jsonb, 'exclusion', array['exclusion', 'pharma employment', 'conflict of interest', 'household']::text[], null, null, 'en', 'Standard pharma conflict-of-interest exclusion. If Yes: CONTINUE only if respondent is consulting for the specific study sponsor; otherwise PLACE ON HOLD and contact Day One Strategy. If No: CONTINUE. Recruiter must capture write-in detail.', true, 'approved', null, null),
  ('EXC-002', 'Have you or any of your immediate family members been employed by or been under contract with any of the following organizations in the past 6 months?', 'multi', '[{"text":"The Federal Government or agencies of the federal government such as VA Hospitals (US ONLY)","terminate":true},{"text":"The US Food and Drug Administration (FDA) (US ONLY)","terminate":true},{"text":"A State Government or agencies of a State Government","terminate":true},{"text":"A marketing or market research department of a company","terminate":true},{"text":"An advertising agency","terminate":true},{"text":"EMA or other Government Agency (FR, DE ONLY)","terminate":true},{"text":"None of the above","terminate":false}]'::jsonb, 'exclusion', array['exclusion', 'government', 'federal', 'FDA', 'advertising', 'market research', 'family']::text[], null, null, 'en', 'Select all that apply. Any selection other than ''None of the above'' = THANK & CLOSE. ''None of the above'' = CONTINUE. Remove EMA option for US-only studies.', true, 'approved', null, null),
  ('EXC-003', 'Are you employed by Kaiser Permanente?', 'single', '[{"text":"Yes","terminate":true},{"text":"No","terminate":false}]'::jsonb, 'exclusion', array['exclusion', 'Kaiser Permanente', 'HCP', 'integrated health system']::text[], array['Healthcare']::text[], null, 'en', 'HCP studies only. Kaiser Permanente employees = THANK & CLOSE. Required for pharmaceutical HCP studies due to closed-formulary system.', true, 'approved', null, null),
  ('DEM-001', 'Please tell me your age.', 'single', '[{"text":"Under 18","terminate":true},{"text":"18 - 30","terminate":false},{"text":"31 - 40","terminate":false},{"text":"41 - 50","terminate":false},{"text":"51 - 60","terminate":false},{"text":"61 - 70","terminate":false},{"text":"71 - 75","terminate":false},{"text":"Over 75","terminate":true}]'::jsonb, 'demographics', array['age', 'demographics', 'patient', 'consumer']::text[], null, null, 'en', 'Patient / consumer studies. Under 18 and Over 75 = THANK & CLOSE (standard Day One template). Do not modify brackets without Research Director sign-off.', true, 'approved', null, null),
  ('DEM-002', 'Which of the following best describes your geographic location?', 'single', '[{"text":"Urban","terminate":false},{"text":"Suburban","terminate":false},{"text":"Rural","terminate":false}]'::jsonb, 'demographics', array['geographic', 'urban', 'suburban', 'rural', 'location']::text[], null, null, 'en', 'INFO ONLY — all options continue. Aim to recruit a geographic mix. Record for profiling.', true, 'approved', null, null),
  ('DEM-003', 'Which of the following best describes you?', 'single', '[{"text":"Male / cisgender","terminate":false},{"text":"Female / cisgender","terminate":false},{"text":"Trans Man (FTM)","terminate":false},{"text":"Trans Woman (MTF)","terminate":false},{"text":"Non-binary","terminate":false},{"text":"Additional gender category / identity not listed (Please Specify)","terminate":false},{"text":"Prefer not to disclose","terminate":false}]'::jsonb, 'demographics', array['gender', 'DEIA', 'identity', 'demographics']::text[], null, null, 'en', 'Standard DEIA gender identity question. INFO ONLY — all options continue. Do not modify wording or options under any circumstances — locked per DEIA policy.', true, 'approved', null, null),
  ('DEM-004', 'Which of the following best describes your race / ethnicity? Select all that apply.', 'multi', '[{"text":"Black or African American","terminate":false},{"text":"Asian or Asian American","terminate":false},{"text":"American Indian, Native Hawaiian, Alaskan Native, or Pacific Islander","terminate":false},{"text":"Hispanic","terminate":false},{"text":"White or Caucasian","terminate":false},{"text":"North African, Middle Eastern or Middle Eastern American","terminate":false},{"text":"Another race (please specify)","terminate":false},{"text":"Prefer not to share","terminate":false}]'::jsonb, 'demographics', array['race', 'ethnicity', 'DEIA', 'diversity']::text[], null, null, 'en', 'Standard DEIA race / ethnicity question. INFO ONLY — all options continue. Diversity targets (illustrative): ~35% Black, ~3% Asian, ~1% Indigenous / Pacific Islander, ~11% Hispanic. Adjust targets per study brief. Do not modify wording — locked per DEIA policy.', true, 'approved', null, null),
  ('SCR-001', 'What type of health insurance do [you / your child or a child in your care] currently have? Select all that apply.', 'multi', '[{"text":"Medicare","terminate":false},{"text":"Medicaid or state / federal assistance","terminate":false},{"text":"TriCare / DoD / Veteran''s Health Administration (VA)","terminate":true},{"text":"Private insurance through your or your spouse / partner''s employer","terminate":false},{"text":"Not insured at this time","terminate":false},{"text":"Don''t know","terminate":false},{"text":"Other (Please specify)","terminate":false}]'::jsonb, 'screening', array['health insurance', 'coverage', 'patient', 'Medicare', 'Medicaid', 'VA']::text[], array['Healthcare']::text[], null, 'en', 'Patient studies only. Routing: Medicare (code 1) OR Private employer insurance (code 4) = MUST SELECT to CONTINUE. Medicaid only (code 2) = HOLD and contact Day One. TriCare/VA (code 3) = THANK & CLOSE. Adjust [you / your child or a child in your care] to match target respondent type.', true, 'approved', null, null),
  ('HCP-001', 'In what state(s) are you licensed to practice?', 'multi', '[{"text":"Alabama","terminate":false},{"text":"Alaska","terminate":false},{"text":"Arizona","terminate":false},{"text":"Arkansas","terminate":false},{"text":"California","terminate":false},{"text":"Colorado","terminate":false},{"text":"Connecticut","terminate":false},{"text":"D.C. - District of Columbia","terminate":false},{"text":"Delaware","terminate":false},{"text":"Florida","terminate":false},{"text":"Georgia","terminate":false},{"text":"Hawaii","terminate":false},{"text":"Idaho","terminate":false},{"text":"Illinois","terminate":false},{"text":"Indiana","terminate":false},{"text":"Iowa","terminate":false},{"text":"Kansas","terminate":false},{"text":"Kentucky","terminate":false},{"text":"Louisiana","terminate":false},{"text":"Maine","terminate":false},{"text":"Maryland","terminate":false},{"text":"Massachusetts","terminate":false},{"text":"Michigan","terminate":false},{"text":"Minnesota","terminate":false},{"text":"Mississippi","terminate":false},{"text":"Missouri","terminate":false},{"text":"Montana","terminate":false},{"text":"Nebraska","terminate":false},{"text":"Nevada","terminate":false},{"text":"New Hampshire","terminate":false},{"text":"New Jersey","terminate":false},{"text":"New Mexico","terminate":false},{"text":"New York","terminate":false},{"text":"North Carolina","terminate":false},{"text":"North Dakota","terminate":false},{"text":"Ohio","terminate":false},{"text":"Oklahoma","terminate":false},{"text":"Oregon","terminate":false},{"text":"Pennsylvania","terminate":false},{"text":"Rhode Island","terminate":false},{"text":"South Carolina","terminate":false},{"text":"South Dakota","terminate":false},{"text":"Tennessee","terminate":false},{"text":"Texas","terminate":false},{"text":"Utah","terminate":false},{"text":"Vermont","terminate":true},{"text":"Virginia","terminate":false},{"text":"Washington","terminate":false},{"text":"West Virginia","terminate":false},{"text":"Wisconsin","terminate":false},{"text":"Wyoming","terminate":false}]'::jsonb, 'hcp_qualification', array['state license', 'geographic', 'HCP', 'US states', 'practice location']::text[], array['Healthcare']::text[], null, 'en', 'HCP studies (US). Vermont = THANK & CLOSE (excluded market for this study type). All other states = CONTINUE. Used to confirm US licensure and geographic distribution.', true, 'approved', null, null),
  ('HCP-002', 'What is your occupation?', 'single', '[{"text":"Physician","terminate":false},{"text":"Nurse Practitioner","terminate":false},{"text":"Physician Assistant","terminate":false},{"text":"Other (write in)","terminate":true}]'::jsonb, 'hcp_qualification', array['occupation', 'HCP role', 'physician', 'NP', 'PA', 'APP']::text[], array['Healthcare']::text[], null, 'en', 'HCP studies. ''Other'' = THANK & CLOSE. Physician routes to board certification (HCP-004); NP/PA routes to APP licensure (HCP-005). May add or remove roles depending on target. Not locked — options may need editing per study.', false, 'approved', null, null),
  ('HCP-003', 'What is your primary medical specialty?', 'single', '[]'::jsonb, 'hcp_qualification', array['specialty', 'medical specialty', 'HCP']::text[], array['Healthcare']::text[], null, 'en', 'HCP studies. Answer options MUST be populated per study based on target specialties. Always include ''Other (write in)'' as final option — typically terminates. Route target specialties to CONTINUE. Not locked — customised per project.', false, 'approved', null, null),
  ('HCP-004', 'Are you board-certified in your specialty?', 'single', '[{"text":"Yes","terminate":false},{"text":"No","terminate":true}]'::jsonb, 'hcp_qualification', array['board certification', 'physician', 'HCP', 'qualification']::text[], array['Healthcare']::text[], null, 'en', 'Physicians only (HCP-002 = Physician). Show via skip logic: display if occupation = Physician. Non-board-certified = THANK & CLOSE.', true, 'approved', null, null),
  ('HCP-005', 'Are you currently licensed and certified to practice in your role?', 'single', '[{"text":"Yes","terminate":false},{"text":"No","terminate":true}]'::jsonb, 'hcp_qualification', array['license', 'certification', 'NP', 'PA', 'APP']::text[], array['Healthcare']::text[], null, 'en', 'APPs only (HCP-002 = NP or PA). Show via skip logic: display if occupation = NP or PA. Not licensed / certified = THANK & CLOSE.', true, 'approved', null, null),
  ('HCP-006', 'What type of activities does your job entail / are you responsible for?', 'multi', '[{"text":"Patient evaluation and monitoring","terminate":false},{"text":"Ordering and managing diagnostics and lab tests","terminate":false},{"text":"Medication and therapy management, including prescribing treatment","terminate":false},{"text":"Patient support and education","terminate":false},{"text":"Care coordination including managing referrals, telehealth follow-ups and handling insurance approvals","terminate":false},{"text":"Other (write in)","terminate":false}]'::jsonb, 'hcp_qualification', array['job activities', 'prescribing', 'APP', 'NP', 'PA', 'scope of practice']::text[], array['Healthcare']::text[], null, 'en', 'APPs only (HCP-002 = NP or PA). Qualification criteria: MUST select ''Medication and therapy management, including prescribing treatment'' AND at least 3 other activities from the first 5 options to CONTINUE. Otherwise THANK & CLOSE.', true, 'approved', null, null),
  ('HCP-007', 'For how many years have you been in practice (excluding your residency and any fellowship training)?', 'numeric', '[]'::jsonb, 'hcp_qualification', array['years in practice', 'experience', 'HCP', 'seniority']::text[], array['Healthcare']::text[], null, 'en', 'HCP studies. Enter integer number of years. Default thresholds: less than 3 years = THANK & CLOSE; more than 35 years = THANK & CLOSE. Adjust thresholds in study-specific screener insert from Lumanity / client brief.', false, 'approved', null, null),
  ('HCP-008', 'Which of the following best describes your primary place of work?', 'single', '[{"text":"Office-based, single specialty group","terminate":false},{"text":"Office-based, multi-specialty group","terminate":false},{"text":"Solo, private practice","terminate":false},{"text":"Community-based, non-teaching hospital","terminate":false},{"text":"Government or VA hospital","terminate":true},{"text":"Office-based, single specialty group with an academic affiliation","terminate":false},{"text":"Office-based, multi-specialty group with an academic affiliation","terminate":false},{"text":"Academic health or medical center","terminate":false},{"text":"Academic, teaching hospital","terminate":false},{"text":"Other (please specify)","terminate":true}]'::jsonb, 'hcp_qualification', array['practice setting', 'community', 'academic', 'HCP', 'place of work']::text[], array['Healthcare']::text[], null, 'en', 'HCP studies. Government/VA = THANK & CLOSE. ''Other'' = THANK & CLOSE. Tag community (options 1–4) and academic (options 6–9) for quota tracking. Recruit a mix unless study specifies otherwise.', false, 'approved', null, null),
  ('HCP-009', 'What proportion of your working time is spent in direct care for patients, as opposed to administrative activities, research, teaching, etc?', 'numeric', '[]'::jsonb, 'hcp_qualification', array['patient care time', 'time allocation', 'HCP', 'clinical activity']::text[], array['Healthcare']::text[], null, 'en', 'HCP studies. Enter percentage (0–100). Minimum clinical time threshold specified by study brief (insert from Lumanity screener). E.g. typical minimum: ≥50% of time in direct patient care.', false, 'approved', null, null),
  ('SCH-001', 'Will you be able to take part in an online interview? You will need to have access to a computer or laptop and be online for the period. We recommend personal computers to avoid any firewall restrictions and a computer or laptop rather than a tablet or mobile phone.', 'single', '[{"text":"Yes","terminate":false},{"text":"No","terminate":true}]'::jsonb, 'scheduling', array['scheduling', 'online interview', 'technology access', 'qual']::text[], null, array['IDI', 'Focus Group']::text[], 'en', 'QUAL ONLY. ''No'' = TERMINATE. Confirms respondent has suitable technology for online interview. Place after qualified respondent confirmation but before diary/scheduling details.', true, 'approved', null, null),
  ('INTRO-004', 'Good morning / afternoon, my name is [INSERT NAME] and I''m calling on behalf of Day One Strategy Ltd., an independent market research agency acting on behalf of a pharmaceutical company. If the study is appropriate for you, we would like you to take part in a [XX]-minute interview which will be conducted online. [INCLUDE IF VIEWED] The research will be observed live by the client company and their associated partners to allow them to gain first-hand insights. The recording may also be made available to people within marketing, medical, new product development and market research roles. [EDIT AS NEEDED] This market research is aimed to gain your views and is not intended to be promotional. Participation is voluntary and you can refuse to answer questions or withdraw from the interview/survey at any time. In appreciation for your time, you will be provided an honorarium of [INCENTIVE] which will be transferred via [INSERT METHOD OF PAYMENT].', 'statement', '[]'::jsonb, 'introduction', array['intro', 'qual', 'recruiter-verbal', 'multi-market', 'EU', 'HCP']::text[], array['Healthcare']::text[], array['IDI', 'Focus Group']::text[], 'en', 'QUAL ONLY. Shorter recruiter intro for multi-market HCP studies. More concise than INTRO-001/002 — suitable when exact condition area is not named upfront. Customise: [INSERT NAME]; [XX] = interview duration; [INCENTIVE]; [INSERT METHOD OF PAYMENT] = transfer method (e.g. bank transfer, voucher).', true, 'approved', null, null),
  ('DISC-002', 'Day One Strategy complies with all laws that protect your personal information including GDPR and the UK Data Protection Act 2018. They follow industry and market research codes of conduct: EphMRA (European Pharmaceutical Market Research Association), ESOMAR (European Society for Opinion and Marketing Research), MRS (Market Research Society), BHBIA (British Healthcare Business Intelligence Association), Intellus and The Insights Association. Our privacy policy can be accessed here: https://dayonestrategy.com/privacy-policy/. Day One is working in partnership with [FIELDWORK PARTNER]. We will not store your name and contact details. In order to have your data removed please contact your recruiter with this job number [PROJECT NUMBER] so they can advise us. Your personal information will only be used for research purposes and will not be passed to any other organisation without your permission with the exception of third-party service providers. You will remain anonymous to the pharmaceutical company unless you give permission to be identified. The processing will be based solely on your consent, which you may withdraw at any time. We won''t keep any personal data you give us for longer than 5 years. This market research is aimed to gain your views and is not intended to be promotional. Participation is voluntary and you can refuse to answer questions or withdraw from the interview/survey at any time.', 'statement', '[]'::jsonb, 'consent', array['disclaimer', 'GDPR', 'EphMRA', 'ESOMAR', 'MRS', 'EU', 'multi-market', 'privacy']::text[], null, null, 'en', 'EU and multi-market studies. GDPR-compliant version of the data disclaimer. Use instead of DISC-001 for non-US or multi-market studies. Customise: [FIELDWORK PARTNER] = partner agency name; [PROJECT NUMBER] = job number. Do not edit legal language.', true, 'approved', null, null),
  ('DISC-003', 'I understand that my personal details and information derived from the Study are processed solely for the purposes of the Study mentioned and in accordance with the applicable personal Data Protection Legislation and Market Research Society Codes of Conduct. My personal information will not be used in any other capacity including, but not limited to advertising, social networking, television, radio etc. I understand that the collection and processing of my personal data is a requirement for the participation in the Study, without which such participation would not be possible and that I can withdraw my consent at any point. I understand that Day One Strategy is the data controller of the personal information processed in the Study and that Day One Strategy will act as single point of contact concerning any query or concern derived from the processing of my personal data. I understand that the time for which my personal information will be retained is 5 years from originating date. I understand that I have the right to access, rectify, delete, restrict or object to the processing, as well as to obtain my personal data in a commonly used format, besides the right to withdraw my consent at any stage of the Study, by contacting Day One @ [INSERT EMAIL]. I understand I also have the right to lodge a complaint with the data protection supervisory authority in my country or region. I understand that my identity and other information obtained during this study will be kept confidential. I understand that my personal data will be shared with third party service providers.

Do you agree to participate on this basis?', 'single', '[{"text":"Yes","terminate":false},{"text":"No","terminate":true}]'::jsonb, 'consent', array['data processing', 'GDPR', 'consent', 'final consent form', 'EU']::text[], null, null, 'en', 'Final consent form data processing consent. ''No'' = TERMINATE. Customise: [INSERT EMAIL] = Day One contact email. EU version includes note about EEA data transfers and Standard Contractual Clauses.', true, 'approved', null, null),
  ('CON-013', 'Day One Strategy is the joint data controller with the sponsoring company. You will be informed of the identity of the sponsoring company at the end of the research. We would prefer not to reveal the name of the healthcare/pharmaceutical company until the end of the interview, just in case knowing this biases any responses. Is this acceptable to you or not?', 'single', '[{"text":"Yes","terminate":false},{"text":"No","terminate":true}]'::jsonb, 'consent', array['consent', 'sponsor blinding', 'EU', 'partial blind', 'joint controller']::text[], array['Healthcare']::text[], null, 'en', 'EU ONLY. Use instead of CON-001 for EU studies where the sponsor is partially blinded (identity revealed at end, not entirely withheld). Day One is joint data controller with the sponsor. ''No'' = THANK & CLOSE. Do not use alongside CON-001 — these are mutually exclusive alternatives.', true, 'approved', null, null),
  ('CON-014', 'This research will be conducted as double-blinded, which means that neither you nor the sponsor of the research will know the identity of the other party. Honoraria paid to physicians for participation in double-blinded market research are excluded from reporting under the Federal Sunshine Act Regulations. In the unlikely event that your identity becomes known to the research sponsor or the sponsor becomes known to you, the payment will then become reportable. Please note that we conduct our research in a manner that will minimize the risk of the research becoming un-blinded, but we want you to be aware of the fact that the payment would be reportable if this were to occur. Therefore, please do not reveal any personal details, such as your name or practice name during the interview.

Are you willing to proceed with the interview on this basis?', 'single', '[{"text":"Yes","terminate":false},{"text":"No","terminate":true}]'::jsonb, 'consent', array['consent', 'sunshine act', 'double-blind', 'HCP', 'US', 'honoraria']::text[], array['Healthcare']::text[], array['IDI', 'Focus Group']::text[], 'en', 'HCP studies only (US double-blinded). Alternative to CON-002 — explains honoraria exclusion from Sunshine Act under double-blind conditions, but notes potential reportability if un-blinded. ''No'' = THANK & CLOSE. Use when legal team prefers this fuller explanation over CON-002.', true, 'approved', null, null),
  ('CON-015', 'This study follows Canadian privacy laws, including the Personal Information Protection and Electronic Documents Act (PIPEDA). This means your personal information will be collected only for the purposes of this research, used securely, and not shared without your consent. You have the right to ask how your information will be used, to access it, or to request corrections.

Do you consent to participate under these conditions?', 'single', '[{"text":"Yes, I consent","terminate":false},{"text":"No, I do not consent","terminate":true}]'::jsonb, 'consent', array['consent', 'PIPEDA', 'Canada', 'data protection']::text[], null, null, 'en', 'Canada only. Required for studies including Canadian respondents. Use alongside DISC-002 or DISC-001. ''No'' = THANK & CLOSE.', true, 'approved', null, null),
  ('CON-016', 'We are being asked to pass on to our client details of adverse events and product quality complaints that are mentioned during market research interviews. Although this is a market research interview/survey and what you say will, of course, be treated in confidence, should you raise during the discussion/survey an adverse event in a specific patient, we will need to report this even if it has already been reported by you directly to the company or the regulatory authorities. In such a situation you will be asked whether you are willing to waive the confidentiality given to you under the Market Research Codes of conduct specifically in relation to that adverse event. Everything else you say during the interview/survey will remain confidential.

Are you happy to proceed with the interview on this basis?', 'single', '[{"text":"Yes","terminate":false},{"text":"No","terminate":true}]'::jsonb, 'consent', array['consent', 'adverse event', 'pharmacovigilance', 'US', 'Italy']::text[], array['Healthcare']::text[], null, 'en', 'US and Italy markets. Shorter / simpler AE reporting consent — alternative to CON-003. ''No'' = THANK & CLOSE. Use CON-003 for UK/other markets; use this version for US/IT. Do not edit wording.', true, 'approved', null, null),
  ('CON-017', 'Pharmaunternehmen sind gesetzlich dazu verpflichtet, Meldungen über Verdachtsfälle von Nebenwirkungen (unerwünschte Ereignisse), andere für die Patientensicherheit relevanten Informationen (wie z.B. Schwangerschaften, Medikationsfehler, etc.) und/oder Produktbeanstandungen zu erfassen und an Gesundheitsbehörden weltweit zu berichten. Sollten Sie uns während der Befragung Informationen zu einer solchen Situation mitteilen, so sind wir verpflichtet, diese Information(en) mit allen uns bekannten Details an das pharmazeutische Unternehmen weiterzuleiten, selbst wenn Sie dieses bereits direkt dem Unternehmen oder den zuständigen Behörden berichtet haben. Diese Meldung erfolgt anonym, ohne Angaben zu Ihrer Person.

Sind Sie auf dieser Basis mit der Teilnahme an diesem Forschungsprojekt einverstanden?', 'single', '[{"text":"Ja","terminate":false},{"text":"Nein","terminate":true}]'::jsonb, 'consent', array['consent', 'adverse event', 'pharmacovigilance', 'Germany', 'German', 'DE']::text[], array['Healthcare']::text[], null, 'de', 'Germany only. German-language AE reporting consent. ''Nein'' = THANK & CLOSE. Always follow with the all-markets English question CON-003 or CON-016 unless study is DE only.', true, 'approved', null, null),
  ('CON-018', 'Day One Strategy may upload the interview to CoLoop for analysis. CoLoop is a closed AI platform used for analysis and your data will not be shared outside of the platform, nor will the AI learn from your data. Privacy policy can be accessed here: https://www.coloop.ai/legal/privacy-policy

Are you happy to proceed with the interview on this basis?', 'single', '[{"text":"Yes","terminate":false},{"text":"No","terminate":false}]'::jsonb, 'consent', array['consent', 'AI analysis', 'CoLoop', 'qual', 'soft opt-out']::text[], null, array['IDI', 'Focus Group']::text[], 'en', 'QUAL ONLY. Standalone CoLoop consent with SOFT OPT-OUT routing — ''No'' = PROCEED BUT DO NOT USE TRANSCRIPT FOR COLOOP UPLOAD. Prioritise ''Yes'' respondents for recruitment. Different from CON-005 (combined Versive/CoLoop/ArgonAI with hard terminate). Use this version when CoLoop is the only AI analysis tool on the study.', true, 'approved', null, null),
  ('CON-019', 'Day One Strategy may upload anonymous transcripts to our licensed model of Chat GPT for analysis purposes. We have a secure license and the AI is not trained on your data. Data is deleted from Chat GPT following the close of the project.

Do you consent to this analysis method?', 'single', '[{"text":"Yes","terminate":false},{"text":"No","terminate":false}]'::jsonb, 'consent', array['consent', 'AI analysis', 'ChatGPT', 'qual', 'soft opt-out']::text[], null, array['IDI', 'Focus Group']::text[], 'en', 'QUAL ONLY. Soft opt-out version of ChatGPT consent — ''No'' = PROCEED BUT DO NOT USE TRANSCRIPT FOR INTERNAL AI AGENT UPLOAD. Prioritise ''Yes'' respondents. Use this version instead of CON-006 when ChatGPT analysis is desirable but not mandatory for participation. Wording is identical to CON-006 — routing is the only difference.', true, 'approved', null, null),
  ('CON-020', 'This interview will be AI moderated – there will not be a live, human moderator present. If possible, please use a computer, instead of a smart phone, for a more seamless experience. The AI moderation makes this engagement easier for you to participate on your own time, just like any other online survey, since a live session does not need to be scheduled. The AI survey is hosted by our partner, Versive. You can access their privacy policy here: https://www.getversive.com/privacy. You will be given the option to respond in text or record a voice answer. Your voice responses will be recorded and used only for research purposes. All recordings will be kept confidential and handled in accordance with data protection laws. You may choose not to provide a voice recording and instead respond in writing if you prefer. Your voice recording may be considered personal data under applicable privacy laws. It will be securely stored, used solely for research analysis, and deleted after the study is completed. You may withdraw your consent to recording at any time.

Are you willing to proceed?', 'single', '[{"text":"Yes","terminate":false},{"text":"No","terminate":true}]'::jsonb, 'consent', array['consent', 'Versive', 'AI moderated', 'voice recording', 'async', 'no live moderator']::text[], null, array['IDI']::text[], 'en', 'Use when Versive is the interview platform (AI-moderated, no live human moderator). Covers both AI moderation consent and voice recording consent in one block. ''No'' = TERMINATE. Approximately 20-minute screener interview duration context. Different from CON-004/CON-005 which are for live Discuss.io sessions.', true, 'approved', null, null),
  ('CON-021', 'Our online survey will be hosted by our partner Inca / Nexxt Intelligence, where you may be probed by their proprietary AI chatbot. You will be given the option to respond in text or provide a voice answer. Should you provide a voice answer, your voice responses will be recorded and used only for research purposes. All recordings will be kept confidential and handled in accordance with data protection laws. You may choose not to provide a voice recording and instead respond in writing if you prefer. Your voice recording may be considered personal data under applicable privacy laws. It will be securely stored, used solely for research analysis, and deleted after the study is completed. You may withdraw your consent to recording at any time. You may access Inca''s privacy policy here: https://www.nexxt.in/privacy

Are you willing to proceed?', 'single', '[{"text":"Yes","terminate":false},{"text":"No","terminate":true}]'::jsonb, 'consent', array['consent', 'INCA', 'Nexxt Intelligence', 'AI chatbot', 'voice recording', 'quant']::text[], null, array['Survey']::text[], 'en', 'QUANT ONLY. Use when Inca / Nexxt Intelligence is the survey platform. Covers AI chatbot probing and voice recording consent. ''No'' = TERMINATE. Keep privacy policy URL current.', true, 'approved', null, null),
  ('CON-022', 'Day One Strategy may upload the interview recordings or transcripts to Argon AI for analysis. Argon AI is a closed platform Day One Strategy uses for analysis of data. The AI models do not learn from your data. Privacy policy can be accessed here: https://argon-ai.com/privacy-policy

Do you consent to this analysis method?', 'single', '[{"text":"Yes","terminate":false},{"text":"No","terminate":true}]'::jsonb, 'consent', array['consent', 'AI analysis', 'ArgonAI', 'Argon', 'qual']::text[], null, array['IDI', 'Focus Group']::text[], 'en', 'QUAL ONLY. Standalone Argon AI consent with hard terminate on ''No''. Updated wording covers both recordings and transcripts. Use this standalone version when Argon is the only AI analysis tool. Compare to CON-005 (combined Versive/CoLoop/ArgonAI).', true, 'approved', null, null),
  ('CON-023', 'Day One Strategy may upload anonymous transcripts from this interview to our InsightBrain Edge platform. The platform is powered by language models from OpenAI and Gemini, accessed through a secure connection. The platform helps us identify themes and patterns more efficiently. A researcher will still review the findings. Your information will only be used for analysis for this project and will not be used to train a general-purpose AI system. All data uploaded to the platform is removed once the project ends.

Do you consent to this analysis method?', 'single', '[{"text":"Yes","terminate":false},{"text":"No","terminate":false}]'::jsonb, 'consent', array['consent', 'AI analysis', 'InsightBrain Edge', 'OpenAI', 'Gemini', 'soft opt-out']::text[], null, array['IDI', 'Focus Group']::text[], 'en', 'QUAL ONLY. Soft opt-out — ''No'' = PROCEED BUT DO NOT UPLOAD TRANSCRIPT FOR AI USE. Prioritise ''Yes'' respondents. Note: platform uses OpenAI and Gemini models via secure connection. Human researcher still reviews all findings.', true, 'approved', null, null),
  ('EXC-004', 'Are you, or any member of your household, employed by the pharmaceutical industry on a full-time or consultancy basis, or is any member of your household employed by a communication or advertising industry related to pharmaceutical products?', 'single', '[{"text":"Yes","terminate":true},{"text":"No","terminate":false}]'::jsonb, 'exclusion', array['exclusion', 'pharma employment', 'conflict of interest', 'hard terminate']::text[], null, null, 'en', 'Hard-terminate version of pharma employment exclusion — ''Yes'' = TERMINATE immediately, no hold. Use instead of EXC-001 when there is no Sanofi/sponsor consultant exception. Note: identical wording to EXC-001, routing is the only difference. Used in multi-market qual studies.', true, 'approved', null, null),
  ('HCP-010', 'In which country do you currently practice?', 'single', '[{"text":"United States","terminate":false},{"text":"Germany","terminate":false},{"text":"Italy","terminate":false},{"text":"Other (Please specify)","terminate":true}]'::jsonb, 'hcp_qualification', array['country', 'geographic', 'HCP', 'multi-market']::text[], array['Healthcare']::text[], null, 'en', 'Multi-market HCP studies. Not locked — country options must be customised to match study markets. ''Other'' = TERMINATE. Randomise country order. First screener question in multi-market designs.', false, 'approved', null, null),
  ('HCP-011', 'Which of the following best describes your sub-specialty within Gastroenterology?', 'single', '[{"text":"General","terminate":false},{"text":"Hepatology","terminate":false},{"text":"Pancreatic disease","terminate":false},{"text":"Inflammatory bowel disease","terminate":false},{"text":"Diseases of esophagus","terminate":false},{"text":"Pediatric Gastroenterology","terminate":false},{"text":"Other (Please specify)","terminate":false}]'::jsonb, 'hcp_qualification', array['sub-specialty', 'gastroenterology', 'gastro', 'HCP']::text[], array['Healthcare']::text[], null, 'en', 'Show only if primary specialty = Gastroenterologist. Routing to CONTINUE/TERMINATE depends on study target. ''Other'' may continue or terminate per study. Not locked — sub-specialty eligibility criteria vary per study.', false, 'approved', null, null),
  ('HCP-012', 'Which of the following best describes your sub-specialty within Pediatrics?', 'single', '[{"text":"General Pediatrics","terminate":true},{"text":"Pediatric Gastroenterology","terminate":false},{"text":"Pediatric Neurology","terminate":true},{"text":"Pediatric Otolaryngology","terminate":true},{"text":"Other (Please specify)","terminate":true}]'::jsonb, 'hcp_qualification', array['sub-specialty', 'pediatrics', 'paediatrics', 'HCP']::text[], array['Healthcare']::text[], null, 'en', 'Show only if primary specialty = Pediatrician. Default routing shown targets Pediatric Gastroenterology studies only. Termination criteria must be adjusted per study — not locked. Add/remove sub-specialties as needed.', false, 'approved', null, null),
  ('HCP-013', 'Which of the following best describes the clinical setting in which you spend the majority of your time treating patients?', 'single', '[{"text":"General Hospital","terminate":false},{"text":"University hospital / academic hospital / teaching hospital","terminate":false},{"text":"Office (non-hospital)","terminate":false},{"text":"Community clinic / practice","terminate":false},{"text":"Nursing home / long-term care setting","terminate":false},{"text":"Other setting (Please specify)","terminate":true}]'::jsonb, 'hcp_qualification', array['practice setting', 'clinical setting', 'community', 'academic', 'HCP', 'multi-market']::text[], array['Healthcare']::text[], null, 'en', 'Multi-market HCP studies. Alternative to HCP-008 (US practice setting). ''Other'' = TERMINATE. Classification: University/academic/teaching hospital = ACADEMIC; General hospital / Office / Community clinic = COMMUNITY. Recruit a mix unless otherwise specified.', false, 'approved', null, null),
  ('HCP-014', 'In which province/city do you currently practice?', 'single', '[{"text":"Abruzzo","terminate":false},{"text":"Basilicata","terminate":false},{"text":"Calabria","terminate":false},{"text":"Campania","terminate":false},{"text":"Emilia Romagna","terminate":false},{"text":"Friuli Venezia Giulia","terminate":false},{"text":"Lazio","terminate":false},{"text":"Liguria","terminate":false},{"text":"Lombardia","terminate":false},{"text":"Marche","terminate":false},{"text":"Molise","terminate":false},{"text":"Piemonte","terminate":false},{"text":"Puglia","terminate":false},{"text":"Sardegna","terminate":false},{"text":"Sicilia","terminate":false},{"text":"Toscana","terminate":false},{"text":"Trentino Alto Adige","terminate":false},{"text":"Umbria","terminate":false},{"text":"Valle d''Aosta","terminate":false},{"text":"Veneto","terminate":false},{"text":"Other (Please specify)","terminate":false}]'::jsonb, 'hcp_qualification', array['province', 'geographic', 'Italy', 'IT', 'HCP']::text[], array['Healthcare']::text[], null, 'it', 'Italy only. Full list of Italian regions. Used to filter HCPs to specific geographic quotas. All options continue — routing per quota requirements. Not locked — quota targets vary per study.', false, 'approved', null, null),
  ('HCP-015', 'In the past [X] months, how many unique patients did you actively manage or treat with each of the following conditions? Please consider total unique patients (not total patient visits) who you see either in-person or virtually.', 'grid', '[{"text":"[CONDITION 1] | Number of unique patients"},{"text":"[CONDITION 2] | Number of unique patients"},{"text":"[CONDITION 3] | Number of unique patients"}]'::jsonb, 'hcp_qualification', array['patient volume', 'patient count', 'condition', 'HCP', 'grid', 'template']::text[], array['Healthcare']::text[], null, 'en', 'TEMPLATE — not ready to use as-is. Patient volume grid for HCP qualification. Customise: [X] = time period (typically 6 or 12 months); conditions list = study-specific disease areas. Termination thresholds (e.g. minimum N patients with target condition) must be specified per study and documented in programming notes.', false, 'approved', null, null),
  ('HCP-016', 'Thinking about your total patients across all conditions, for how many patients did you initiate biologic therapy in the past [X] months? Please think about initiating biologic therapy for any condition. Consider all patients whom you see or treat either in-person or virtually.', 'numeric', '[]'::jsonb, 'hcp_qualification', array['biologic therapy', 'treatment initiation', 'HCP', 'prescribing', 'biologics']::text[], array['Healthcare']::text[], null, 'en', 'HCP studies involving biologic therapies. Enter integer number of patients. Customise: [X] = time period (typically 6 months). Terminate if = 0 (no biologic initiations). Confirm threshold with client brief.', false, 'approved', null, null)
on conflict (display_id) where display_id is not null
do update set
  question_text = excluded.question_text,
  question_type = excluded.question_type,
  answer_options = excluded.answer_options,
  category = excluded.category,
  tags = excluded.tags,
  sector = excluded.sector,
  methodology = excluded.methodology,
  language = excluded.language,
  notes = excluded.notes,
  is_locked = excluded.is_locked,
  status = excluded.status,
  updated_at = now();
